stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
  only:
    - merge_requests
    - branches

test_job:
  stage: test
  script:
    - echo "Running tests..."
  only:
    - merge_requests
    - branches
